### ISSUE TITLE
Crash with Savage & Ravage?

### ISSUE THREAD

**Issue by Jukabofy** [Commoble/workshopsofdoom#5]
[crash-2022-12-12_10.37.52-server.txt](https://github.com/Commoble/workshopsofdoom/files/10209606/crash-2022-12-12_10.37.52-server.txt)
This is the crash
I was walking and then it crashed

**Comment by Commoble** [comment]
It's a bug with savage and ravage, it crashes other mods too (mainly whenever a pillager is spawned by a worldgen feature), the savage and ravage devs have to fix it themselves, nothing I can do on my end

https://github.com/team-abnormals/savage-and-ravage/issues/119

**Comment by Jukabofy** [comment]
Oh, so, its random
thanks for the answer
Hope they fix it
