### ISSUE TITLE
Tweak generation

### ISSUE THREAD

**Issue by Jukabofy** [Commoble/workshopsofdoom#6]
Structures seems to spawn way too frecuently
Sometimes they generate a little messy
Sometimes they are floating

**Comment by Commoble** [comment]
Can't do much about the messy generation or floatiness (I could turn off terraforming for them which would make them less messy but more floaty) but they're definitely spawning too often, I made a mistake when porting the structures to 1.19

**Comment by Jukabofy** [comment]
Thank you, I don't think messy generation is a big problem
just structures being often

**Comment by Yourname942** [comment]
Is it possible to alter these settings via a datapack, mixin, or even modifying the source file? Thank you.

**Comment by Commoble** [comment]
> Is it possible to alter these settings via a datapack, mixin, or even modifying the source file? Thank you.

yeah you can override the structure jsons to not use terrain adaptation

https://github.com/Commoble/workshopsofdoom/blob/main/src/generated/resources/data/workshopsofdoom/worldgen/structure/badlands_mines.json

They'll be less messy but more floaty
