### ISSUE TITLE
Workshops Of Doom Failed to Load Correctly

### ISSUE THREAD

**Issue by Mewcenary** [Commoble/workshopsofdoom#7]
Hello! Can you please help me, I am not sure if I can fix it on my end or not.
----------------------------------------------
Minecraft: 1.18.2
Java: 17
Forge Installer: 1.18.2-forge-40.2.0
Mod: workshopsofdoom-1.18.1-2.1.0.1
CP:  Windows 11 Home
Processor: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz 2.90 GHz
Installed RAM: 32.0 GB (31.9 GB usable)
System type: 64-bit operating system, x64-based processor
----------------------------------------------

[crash-2023-04-16_16.18.21-fml.txt](https://github.com/Commoble/workshopsofdoom/files/11244912/crash-2023-04-16_16.18.21-fml.txt)

**Comment by Commoble** [comment]
I never updated the mod to 1.18.2, it doesn't work on 1.18.2

**Comment by Mewcenary** [comment]
> I never updated the mod to 1.18.2, it doesn't work on 1.18.2

T^T PLEASEEEEEEEEEEEEEEEEEEEEE make it for 18.2..... don't forsake me....
